-- Supabase Schema for AI Trading Bot Factory

-- 1. Bots Table (DNA and Lifecycle)
CREATE TABLE IF NOT EXISTS bots (
  id TEXT PRIMARY KEY,
  version TEXT NOT NULL,
  generation INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL, -- 'Draft', 'Candidate', 'Published', 'Deployed'
  dna JSONB NOT NULL, -- Full BotDNA object
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Evaluations Table (Backtest Results)
CREATE TABLE IF NOT EXISTS evaluations (
  id TEXT PRIMARY KEY,
  bot_id TEXT REFERENCES bots(id) ON DELETE CASCADE,
  period TEXT NOT NULL, -- '1y', '2y', '5y'
  metrics JSONB NOT NULL, -- {totalReturn, marketReturn, maxDrawdown, sharpeRatio, winRate, tradeCount}
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Deployments Table (Virtual Portfolio)
CREATE TABLE IF NOT EXISTS deployments (
  id TEXT PRIMARY KEY,
  bot_id TEXT REFERENCES bots(id) ON DELETE CASCADE,
  bot_version TEXT NOT NULL,
  status TEXT NOT NULL, -- 'Active', 'Paused', 'Stopped'
  allocated_capital_nok NUMERIC NOT NULL,
  allocated_pct NUMERIC,
  symbol TEXT DEFAULT 'SPY',
  benchmark_symbol TEXT DEFAULT '^GSPC',
  interval TEXT DEFAULT '1wk',
  live_balance_nok NUMERIC,
  last_processed_at TEXT,
  performance JSONB, -- DeploymentPerformance
  equity_curve JSONB, -- DeploymentEquityPoint[]
  live_equity_curve JSONB, -- DeploymentEquityPoint[]
  transactions JSONB, -- DeploymentTransaction[]
  backtest_performance JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Evolution Events (Factory Log)
CREATE TABLE IF NOT EXISTS evolution_events (
  id TEXT PRIMARY KEY,
  cycle_number INTEGER NOT NULL,
  type TEXT NOT NULL, -- 'spawn', 'mutate', etc.
  bot_id TEXT REFERENCES bots(id) ON DELETE CASCADE,
  source_bot_ids JSONB,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Factory State
CREATE TABLE IF NOT EXISTS factory_state (
  id INTEGER PRIMARY KEY DEFAULT 1,
  cycle_number INTEGER NOT NULL DEFAULT 0,
  active_bot_ids JSONB DEFAULT '[]',
  last_run_at TIMESTAMP WITH TIME ZONE,
  settings JSONB DEFAULT '{"maxPopulation": 10, "cycleIntervalHours": 24, "ollamaEnabled": true}',
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  CONSTRAINT single_row CHECK (id = 1)
);

-- Enable RLS (Row Level Security)
ALTER TABLE bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE deployments ENABLE ROW LEVEL SECURITY;
ALTER TABLE evolution_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE factory_state ENABLE ROW LEVEL SECURITY;

-- Create Policies (Public access for now, as requested for local-first transition)
CREATE POLICY "Public Read Access" ON bots FOR SELECT USING (true);
CREATE POLICY "Public Write Access" ON bots FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Access" ON bots FOR UPDATE USING (true);
CREATE POLICY "Public Delete Access" ON bots FOR DELETE USING (true);

CREATE POLICY "Public Read Access" ON evaluations FOR SELECT USING (true);
CREATE POLICY "Public Write Access" ON evaluations FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Access" ON evaluations FOR UPDATE USING (true);

CREATE POLICY "Public Read Access" ON deployments FOR SELECT USING (true);
CREATE POLICY "Public Write Access" ON deployments FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Access" ON deployments FOR UPDATE USING (true);

CREATE POLICY "Public Read Access" ON evolution_events FOR SELECT USING (true);
CREATE POLICY "Public Write Access" ON evolution_events FOR INSERT WITH CHECK (true);

CREATE POLICY "Public Read Access" ON factory_state FOR SELECT USING (true);
CREATE POLICY "Public Write Access" ON factory_state FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Access" ON factory_state FOR UPDATE USING (true);

-- 6. Crisis Monitor — KPI-tidsserie (diagrammer / ROC), matcher kinvest_monitor.py (SQLite)
CREATE TABLE IF NOT EXISTS crisis_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts_utc TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  taiwan_reserve_pct NUMERIC,
  korea_reserve_pct NUMERIC,
  helium_price_usd NUMERIC,
  jkm_price_usd NUMERIC,
  twd_usd NUMERIC,
  nasdaq_proxy NUMERIC,
  helium_roc_24h_pct NUMERIC,
  helium_roc_7d_pct NUMERIC,
  twd_roc_24h_pct NUMERIC,
  nasdaq_roc_24h_pct NUMERIC,
  crisis_index NUMERIC NOT NULL,
  critical_sell BOOLEAN NOT NULL DEFAULT FALSE,
  asian_grid_lock BOOLEAN NOT NULL DEFAULT FALSE,
  notes_json JSONB
);

CREATE INDEX IF NOT EXISTS idx_crisis_log_ts_utc ON crisis_log (ts_utc DESC);

-- 7. Crisis Monitor — heartbeat (operatør / web-status)
CREATE TABLE IF NOT EXISTS engine_status (
  id INTEGER PRIMARY KEY DEFAULT 1,
  last_heartbeat TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'INITIALIZING',
  crisis_index NUMERIC,
  critical_sell BOOLEAN DEFAULT FALSE,
  asian_grid_lock BOOLEAN DEFAULT FALSE,
  taiwan_reserve_pct NUMERIC,
  helium_price_usd NUMERIC,
  twd_usd NUMERIC,
  CONSTRAINT engine_status_single_row CHECK (id = 1)
);

INSERT INTO engine_status (id, last_heartbeat, status)
VALUES (1, NOW(), 'INITIALIZING')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE crisis_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE engine_status ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Crisis log public read" ON crisis_log FOR SELECT USING (true);
CREATE POLICY "Crisis log public insert" ON crisis_log FOR INSERT WITH CHECK (true);

CREATE POLICY "Engine status public read" ON engine_status FOR SELECT USING (true);
CREATE POLICY "Engine status public insert" ON engine_status FOR INSERT WITH CHECK (true);
CREATE POLICY "Engine status public update" ON engine_status FOR UPDATE USING (true);
