CREATE TABLE IF NOT EXISTS crisis_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ts_utc TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  taiwan_reserve_pct NUMERIC,
  korea_reserve_pct NUMERIC,
  helium_price_usd NUMERIC,
  jkm_price_usd NUMERIC,
  twd_usd NUMERIC,
  nasdaq_proxy NUMERIC,
  helium_roc_24h_pct NUMERIC,
  helium_roc_7d_pct NUMERIC,
  twd_roc_24h_pct NUMERIC,
  nasdaq_roc_24h_pct NUMERIC,
  crisis_index NUMERIC NOT NULL,
  critical_sell BOOLEAN NOT NULL DEFAULT FALSE,
  asian_grid_lock BOOLEAN NOT NULL DEFAULT FALSE,
  notes_json JSONB
);

CREATE INDEX IF NOT EXISTS idx_crisis_log_ts_utc ON crisis_log (ts_utc DESC);

CREATE TABLE IF NOT EXISTS engine_status (
  id INTEGER PRIMARY KEY DEFAULT 1,
  last_heartbeat TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'INITIALIZING',
  crisis_index NUMERIC,
  critical_sell BOOLEAN DEFAULT FALSE,
  asian_grid_lock BOOLEAN DEFAULT FALSE,
  CONSTRAINT engine_status_single_row CHECK (id = 1)
);

INSERT INTO engine_status (id, last_heartbeat, status)
VALUES (1, NOW(), 'INITIALIZING')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE crisis_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE engine_status ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Crisis log public read" ON crisis_log;
DROP POLICY IF EXISTS "Crisis log public insert" ON crisis_log;
CREATE POLICY "Crisis log public read" ON crisis_log FOR SELECT USING (true);
CREATE POLICY "Crisis log public insert" ON crisis_log FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Engine status public read" ON engine_status;
DROP POLICY IF EXISTS "Engine status public insert" ON engine_status;
DROP POLICY IF EXISTS "Engine status public update" ON engine_status;
CREATE POLICY "Engine status public read" ON engine_status FOR SELECT USING (true);
CREATE POLICY "Engine status public insert" ON engine_status FOR INSERT WITH CHECK (true);
CREATE POLICY "Engine status public update" ON engine_status FOR UPDATE USING (true);
